services:
  scintilla:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scintilla-app
    ports:
      - "4005:4005"
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./src:/app/src         
    restart: unless-stopped
    networks:
      - scintilla-network

networks:
  scintilla-network:
    driver: bridge
